### ISSUE TITLE
Fail to import SNPs from genlight object 

### ISSUE THREAD

**Issue by IdoBar** [hemstrow/snpR#49]
Hi,

This package looks very interesting, but I can't get passed the first step of importing the SNPs in...
My SNPs are in `genlight` format (imported by [dartR](http://georges.biomatix.org/dartR)), with population and metadata slots.
When I try to import it I get the following:
```
convert_genlight(glsub)
Error in genotypes[1, 1] : object of type 'closure' is not subsettable
```
It does work when I export the SNPs as a VCF file and read it from there.

Any ideas?

Thanks, Ido

**Comment by hemstrow** [comment]
I'd be happy to take a look at this! I'm always glad to do bug fixes.

Would you feel comfortable sending me a reproducible example? Ideally R code and the `genlight` object you are using. You can save the object with `saveRDS()` and attach it in a reply here. A small subset of your data is perfectly fine as long as it produces the error!

**Comment by hemstrow** [comment]
@IdoBar Actually, I think I've got it fixed. The fix is on the dev version now (installable with `remotes::install_github("hemstrow/snpR", ref = "dev") and I'm going to push it as a hotfix to the master branch soon (hopefully later today).

**Comment by IdoBar** [comment]
Just checked it and it still fails, this time with a different error:
```
> papaya_snpr <- snpR::convert_genlight(glsub)
Error in match(x, table, nomatch = 0L) : 
  'match' requires vector arguments
```

**Comment by hemstrow** [comment]
@IdoBar Hmm, given that it's working with my test data without issue, I really would need to have some data with which I can reproduce the error. Would you be able to provide a small subset of your data for me to test with that still errors during conversion? You can either attach it here or email it to me at whemstro@ucdavis.edu.

**Comment by IdoBar** [comment]
I've updated my comment above with an example dataset.

**Comment by hemstrow** [comment]
Thanks @IdoBar! The issue was that the object you sent was a new-fangled `dartR` object instead of a typical `genlight` object, which was causing an old `"genlight" %in% class(x)` that hadn't been revised to `is(x, "genlight")` to fail. With that fixed, I have no problems converting your object with:

```
papaya_snpr <- convert_genlight(glsub)
```

This should be fixed now on the `dev` branch, installable with `remotes::install_github("hemstrow/snpR", ref = "dev")`. Thanks for bringing this to my attention!

**Comment by IdoBar** [comment]
Thanks for the quick reply @hemstrow !
I tried installing the latest dev branch, but it still appears as v1.2.7.9001 and there's no difference from the previous dev version.

Thanks, Ido

**Comment by hemstrow** [comment]
@IdoBar I neglected to update the version number, but I do see that the changes are present in the dev branch of the repo and they *should* be there on re-install! You shouldn't need to specify `force = TRUE` for `remotes::install_github()`, but if it's saying no changes you might want to try that. If it persists in not wanting to update, I'm happy to push the change to the master branch as a hotfix and make sure the version number is updated!

**Comment by IdoBar** [comment]
Yes, I double-checked it after restarting the R session and it does work as expected.

Many thanks, Ido

**Comment by hemstrow** [comment]
Excellent, I'm glad to hear it! Please do let me know if you run into any other issues or have features that you'd like to see implemented.
